define(["../../template",""],function(o){return o("common/pop_window/pop_window",function(o,i){"use strict";var n=this,s=n.$helpers,p=n.$string,c=o.title,t="";t+='<div class="common-pop-window"> <div class="common-pop-title"><span>';t+=p(c);t+='</span><a href="javascript:;" class="close close-window-hook"></a></div>  <div class="common-pop-wrap"> </div> </div> <div class="common-pop-mask"></div>';return new String(t)})});

/** If u are interested in our code and would like to make it robust, just contact us^^ <@音乐前端> **/
/** Generated by M3D. **/